import type { Metadata } from "next";
import "./globals.css";
import Layout from "@/components/Layout";
import { ShopingCartContextProvider } from "@/context/ShopingCartContext";


export const metadata: Metadata = {
  title: "Majid Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <ShopingCartContextProvider>
      <Layout>
        {children}
        </Layout>
      </ShopingCartContextProvider>
        
      </body>
    </html>
  );
}
